[package]
name = "tofu"
version = "0.1.0"
authors = ["Matthew Chase Whittemore <mcwhittemore@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
image = "0.23.14"
